//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExBuddy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExBuddy.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve cordial data, if this continues, please report logs to ExMatt..
        /// </summary>
        internal static string Cordinal_NullSpellData {
            get {
                return ResourceManager.GetString("Cordinal_NullSpellData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: Death Location: {0}, AetheryteId: {1}.
        /// </summary>
        internal static string DefaultReturnStrategy_Default {
            get {
                return ResourceManager.GetString("DefaultReturnStrategy_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Flight.
        /// </summary>
        internal static string EnableFlight_PluginName {
            get {
                return ResourceManager.GetString("EnableFlight_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout while depositing items into free company chest..
        /// </summary>
        internal static string ExCompanyChestDeposit_Timeout {
            get {
                return ResourceManager.GetString("ExCompanyChestDeposit_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} already disabled..
        /// </summary>
        internal static string ExDisablePlugins_Disabled {
            get {
                return ResourceManager.GetString("ExDisablePlugins_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling Plugins: .
        /// </summary>
        internal static string ExDisablePlugins_Disabling {
            get {
                return ResourceManager.GetString("ExDisablePlugins_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling Plugin {0}.
        /// </summary>
        internal static string ExDisablePlugins_Disabling2 {
            get {
                return ResourceManager.GetString("ExDisablePlugins_Disabling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} already enabled..
        /// </summary>
        internal static string ExEnablePlugins_Enabled {
            get {
                return ResourceManager.GetString("ExEnablePlugins_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Plugins: .
        /// </summary>
        internal static string ExEnablePlugins_Enabling {
            get {
                return ResourceManager.GetString("ExEnablePlugins_Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Plugin {0}.
        /// </summary>
        internal static string ExEnablePlugins_Enabling2 {
            get {
                return ResourceManager.GetString("ExEnablePlugins_Enabling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fish are amiss at all of the FishSpots..
        /// </summary>
        internal static string ExFish_AmissFish {
            get {
                return ResourceManager.GetString("ExFish_AmissFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fish sense something amiss. Perhaps it is time to try another location..
        /// </summary>
        internal static string ExFish_AmissFish2 {
            get {
                return ResourceManager.GetString("ExFish_AmissFish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fish sense something amiss!.
        /// </summary>
        internal static string ExFish_AmissFish3 {
            get {
                return ResourceManager.GetString("ExFish_AmissFish3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during bait selection..
        /// </summary>
        internal static string ExFish_BaitSelectError {
            get {
                return ResourceManager.GetString("ExFish_BaitSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This zone has been blacklisted, please fish somewhere else and then restart the profile..
        /// </summary>
        internal static string ExFish_BlackList {
            get {
                return ResourceManager.GetString("ExFish_BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding &apos;{0}&apos;, doesn&apos;t match any item in the database..
        /// </summary>
        internal static string ExFish_CannotFindBait {
            get {
                return ResourceManager.GetString("ExFish_CannotFindBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing FishSpots....
        /// </summary>
        internal static string ExFish_ChangeSpots {
            get {
                return ResourceManager.GetString("ExFish_ChangeSpots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the proper weather....
        /// </summary>
        internal static string ExFish_CheckWeather {
            get {
                return ResourceManager.GetString("ExFish_CheckWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting {0} -&gt; Value: {1}, Required: {2}.
        /// </summary>
        internal static string ExFish_Collecting {
            get {
                return ResourceManager.GetString("ExFish_Collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Collector&apos;s Glove.
        /// </summary>
        internal static string ExFish_CollectorsGlove {
            get {
                return ResourceManager.GetString("ExFish_CollectorsGlove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declining {0} -&gt; Value: {1}, Required: {2}.
        /// </summary>
        internal static string ExFish_Declining {
            get {
                return ResourceManager.GetString("ExFish_Declining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fished {0} of {1} fish at this FishSpot..
        /// </summary>
        internal static string ExFish_Fish {
            get {
                return ResourceManager.GetString("ExFish_Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You land(?: a| an)? (.+) measuring (\d{1,4}\.\d) ilms!.
        /// </summary>
        internal static string ExFish_FishRegex {
            get {
                return ResourceManager.GetString("ExFish_FishRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will fish for .
        /// </summary>
        internal static string ExFish_InitFishSpot {
            get {
                return ResourceManager.GetString("ExFish_InitFishSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  fish before moving again..
        /// </summary>
        internal static string ExFish_InitFishSpot2 {
            get {
                return ResourceManager.GetString("ExFish_InitFishSpot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: &apos;{0}&apos; is not considered bait..
        /// </summary>
        internal static string ExFish_IsNotBait {
            get {
                return ResourceManager.GetString("ExFish_IsNotBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mooching, this is mooch {0} of {1} mooches..
        /// </summary>
        internal static string ExFish_Mooch {
            get {
                return ResourceManager.GetString("ExFish_Mooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mooching, this will be the only mooch..
        /// </summary>
        internal static string ExFish_Mooch2 {
            get {
                return ResourceManager.GetString("ExFish_Mooch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cordial available, buy more .
        /// </summary>
        internal static string ExFish_NoCordial {
            get {
                return ResourceManager.GetString("ExFish_NoCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not sense any fish here..
        /// </summary>
        internal static string ExFish_NoSenceOfFish {
            get {
                return ResourceManager.GetString("ExFish_NoSenceOfFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not sense any fish here, trying next location..
        /// </summary>
        internal static string ExFish_NoSenceOfFish2 {
            get {
                return ResourceManager.GetString("ExFish_NoSenceOfFish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the specified bait:.
        /// </summary>
        internal static string ExFish_NotHaveBait {
            get {
                return ResourceManager.GetString("ExFish_NotHaveBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patience activated.
        /// </summary>
        internal static string ExFish_Patience {
            get {
                return ResourceManager.GetString("ExFish_Patience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released .
        /// </summary>
        internal static string ExFish_Release {
            get {
                return ResourceManager.GetString("ExFish_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting fish count....
        /// </summary>
        internal static string ExFish_ResetCount {
            get {
                return ResourceManager.GetString("ExFish_ResetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting mooch level..
        /// </summary>
        internal static string ExFish_ResetMooch {
            get {
                return ResourceManager.GetString("ExFish_ResetMooch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitting .
        /// </summary>
        internal static string ExFish_Sit {
            get {
                return ResourceManager.GetString("ExFish_Sit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Snagging.
        /// </summary>
        internal static string ExFish_Snagging {
            get {
                return ResourceManager.GetString("ExFish_Snagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffled fish spots.
        /// </summary>
        internal static string ExFish_SuffleSpots {
            get {
                return ResourceManager.GetString("ExFish_SuffleSpots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TugType detected. Using {1}.
        /// </summary>
        internal static string ExFish_TugType {
            get {
                return ResourceManager.GetString("ExFish_TugType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using bait -&gt; .
        /// </summary>
        internal static string ExFish_UseBait {
            get {
                return ResourceManager.GetString("ExFish_UseBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Cordial -&gt; Waiting (sec): {0}, CurrentGP: {1}.
        /// </summary>
        internal static string ExFish_UseCordial {
            get {
                return ResourceManager.GetString("ExFish_UseCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using cordial when it becomes available.
        /// </summary>
        internal static string ExFish_UseCordialWhenAvailable {
            get {
                return ResourceManager.GetString("ExFish_UseCordialWhenAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviating from course to waypoint: {0}.
        /// </summary>
        internal static string ExFlyTo_Deviating {
            get {
                return ResourceManager.GetString("ExFlyTo_Deviating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in range -&gt; Start: {0}, End: {1}.
        /// </summary>
        internal static string ExFlyTo_Distance {
            get {
                return ResourceManager.GetString("ExFlyTo_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using existing FlightPath {0} from {1} to {2}.
        /// </summary>
        internal static string ExFlyTo_ExsistingPath {
            get {
                return ResourceManager.GetString("ExFlyTo_ExsistingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Path.
        /// </summary>
        internal static string ExFlyTo_GenPath {
            get {
                return ResourceManager.GetString("ExFlyTo_GenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing took {0} ms.
        /// </summary>
        internal static string ExFlyTo_Landing {
            get {
                return ResourceManager.GetString("ExFlyTo_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to waypoint: {0}.
        /// </summary>
        internal static string ExFlyTo_MoveToWaypoint {
            get {
                return ResourceManager.GetString("ExFlyTo_MoveToWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to waypoint [{0}]: {1}.
        /// </summary>
        internal static string ExFlyTo_MoveToWaypoint2 {
            get {
                return ResourceManager.GetString("ExFlyTo_MoveToWaypoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building new FlightPath {0} from {1} to {2}.
        /// </summary>
        internal static string ExFlyTo_NewPath {
            get {
                return ResourceManager.GetString("ExFlyTo_NewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No viable path computed for {0}..
        /// </summary>
        internal static string ExFlyTo_NoViablePath {
            get {
                return ResourceManager.GetString("ExFlyTo_NoViablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklisting node so that we don&apos;t retarget -&gt; .
        /// </summary>
        internal static string ExGather_BlackListNode {
            get {
                return ResourceManager.GetString("ExGather_BlackListNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using cordial when it becomes available.
        /// </summary>
        internal static string ExGather_Cordial {
            get {
                return ResourceManager.GetString("ExGather_Cordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cordial available, buy more .
        /// </summary>
        internal static string ExGather_CordialNotAvailable {
            get {
                return ResourceManager.GetString("ExGather_CordialNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Cordial -&gt; Waiting (sec): {0}, CurrentGP: {1}.
        /// </summary>
        internal static string ExGather_CordialUse {
            get {
                return ResourceManager.GetString("ExGather_CordialUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using .
        /// </summary>
        internal static string ExGather_CordialUsing {
            get {
                return ResourceManager.GetString("ExGather_CordialUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordial not enabled.  To enable cordial use, add the &apos;cordialType&apos; attribute with value &apos;Auto&apos;, &apos;Cordial&apos;, or &apos;HiCordial&apos;.
        /// </summary>
        internal static string ExGather_DisabledCordial {
            get {
                return ResourceManager.GetString("ExGather_DisabledCordial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before gather cordial not enabled.  To enable, add the &apos;cordialTime&apos; attribute with value &apos;BeforeGather&apos;, &apos;IfNeeded&apos;, &apos;IfNeededOrAfter&apos;, or &apos;Auto&apos;.
        /// </summary>
        internal static string ExGather_DisabledCordialBeforeGather {
            get {
                return ResourceManager.GetString("ExGather_DisabledCordialBeforeGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using a distance of greater than 3.5 is not supported, change the value and restart the profile..
        /// </summary>
        internal static string ExGather_Distance {
            get {
                return ResourceManager.GetString("ExGather_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to furthest vector in hotspot -&gt; .
        /// </summary>
        internal static string ExGather_DistanceHotSpot {
            get {
                return ResourceManager.GetString("ExGather_DistanceHotSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance to furthest visible game object -&gt; .
        /// </summary>
        internal static string ExGather_DistanceObject {
            get {
                return ResourceManager.GetString("ExGather_DistanceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened during gathering and we did not complete the sequence.
        /// </summary>
        internal static string ExGather_ExecutePoiLogic {
            get {
                return ResourceManager.GetString("ExGather_ExecutePoiLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished gathering from {0} with {1} GP at {2} ET.
        /// </summary>
        internal static string ExGather_Finished {
            get {
                return ResourceManager.GetString("ExGather_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} of {1} loops..
        /// </summary>
        internal static string ExGather_FinishedLoop {
            get {
                return ResourceManager.GetString("ExGather_FinishedLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory is full and no shards/crystals/clusters to gather. Gathering complete..
        /// </summary>
        internal static string ExGather_FullInventory {
            get {
                return ResourceManager.GetString("ExGather_FullInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatherSpot set -&gt; .
        /// </summary>
        internal static string ExGather_GatherSpotSet {
            get {
                return ResourceManager.GetString("ExGather_GatherSpotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started gathering from {0} with {1}/{2} GP at {3} ET.
        /// </summary>
        internal static string ExGather_GatherStart {
            get {
                return ResourceManager.GetString("ExGather_GatherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Window didn&apos;t open: Retrying. {0}/5.
        /// </summary>
        internal static string ExGather_GatherWindow {
            get {
                return ResourceManager.GetString("ExGather_GatherWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Window didn&apos;t open: Re-attempting to move into place. {0}/5.
        /// </summary>
        internal static string ExGather_GatherWindow2 {
            get {
                return ResourceManager.GetString("ExGather_GatherWindow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP recovering faster than cordial cooldown, waiting for GP. Seconds: {0}.
        /// </summary>
        internal static string ExGather_GPRecover {
            get {
                return ResourceManager.GetString("ExGather_GPRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for GP.
        /// </summary>
        internal static string ExGather_GPWait {
            get {
                return ResourceManager.GetString("ExGather_GPWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for GP -&gt; Seconds: {0}, Current GP: {1}, WaitForGP: {2}.
        /// </summary>
        internal static string ExGather_GPWaitDetailed {
            get {
                return ResourceManager.GetString("ExGather_GPWaitDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to hotspot {0}{1}.
        /// </summary>
        internal static string ExGather_MoveToHotSpot {
            get {
                return ResourceManager.GetString("ExGather_MoveToHotSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any nodes and can not confirm hotspot is empty via object detection, trying again from center of hotspot..
        /// </summary>
        internal static string ExGather_NoAvailableNode {
            get {
                return ResourceManager.GetString("ExGather_NoAvailableNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node on blacklist, waiting until we move out of range or it clears..
        /// </summary>
        internal static string ExGather_NodeBlacklist {
            get {
                return ResourceManager.GetString("ExGather_NodeBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node removed from blacklist..
        /// </summary>
        internal static string ExGather_NodeBlacklistRemoved {
            get {
                return ResourceManager.GetString("ExGather_NodeBlacklistRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interacting with node.
        /// </summary>
        internal static string ExGather_NodeInteract {
            get {
                return ResourceManager.GetString("ExGather_NodeInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node is gone.
        /// </summary>
        internal static string ExGather_NodeIsGone {
            get {
                return ResourceManager.GetString("ExGather_NodeIsGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Reset, Reason: Ran out of range.
        /// </summary>
        internal static string ExGather_NodeReset {
            get {
                return ResourceManager.GetString("ExGather_NodeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node set -&gt; .
        /// </summary>
        internal static string ExGather_NodeSet {
            get {
                return ResourceManager.GetString("ExGather_NodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough gp to use rotation, cancelling gather..
        /// </summary>
        internal static string ExGather_NotEnoughGP {
            get {
                return ResourceManager.GetString("ExGather_NotEnoughGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough time to gather, will still make an attempt..
        /// </summary>
        internal static string ExGather_NotEnoughTime {
            get {
                return ResourceManager.GetString("ExGather_NotEnoughTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an item to gather, moving on..
        /// </summary>
        internal static string ExGather_NothingToGather {
            get {
                return ResourceManager.GetString("ExGather_NothingToGather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not find item by slot or name, gathering.
        /// </summary>
        internal static string ExGather_NothingToGather2 {
            get {
                return ResourceManager.GetString("ExGather_NothingToGather2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instead..
        /// </summary>
        internal static string ExGather_NothingToGather3 {
            get {
                return ResourceManager.GetString("ExGather_NothingToGather3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get types, Loading Known Rotations..
        /// </summary>
        internal static string ExGather_NoTypeSpecified {
            get {
                return ResourceManager.GetString("ExGather_NoTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating rotation based off {0}.
        /// </summary>
        internal static string ExGather_Rotationbaseoff {
            get {
                return ResourceManager.GetString("ExGather_Rotationbaseoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating rotation based off GatherIncrease: &apos;{0}&apos;.
        /// </summary>
        internal static string ExGather_RotationbaseoffGatherIncrease {
            get {
                return ResourceManager.GetString("ExGather_RotationbaseoffGatherIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Estimate -&gt; Old: {0} , New: {1}.
        /// </summary>
        internal static string ExGather_RotationEstimate {
            get {
                return ResourceManager.GetString("ExGather_RotationEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Rotation -&gt; {0}, GP: {1}, Time: {2}.
        /// </summary>
        internal static string ExGather_RotationLoad {
            get {
                return ResourceManager.GetString("ExGather_RotationLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation did not change.
        /// </summary>
        internal static string ExGather_RotationNotChange {
            get {
                return ResourceManager.GetString("ExGather_RotationNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find rotation, using RegularNode instead..
        /// </summary>
        internal static string ExGather_RotationNotFound {
            get {
                return ResourceManager.GetString("ExGather_RotationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Override -&gt; Old: {0} , New: {1}.
        /// </summary>
        internal static string ExGather_RotationOverride {
            get {
                return ResourceManager.GetString("ExGather_RotationOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to gather is unknown, we are overriding the rotation to ensure we can collect it..
        /// </summary>
        internal static string ExGather_RotationOverriding {
            get {
                return ResourceManager.GetString("ExGather_RotationOverriding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation reset -&gt; .
        /// </summary>
        internal static string ExGather_RotationReset {
            get {
                return ResourceManager.GetString("ExGather_RotationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using rotation -&gt; .
        /// </summary>
        internal static string ExGather_RotationUse {
            get {
                return ResourceManager.GetString("ExGather_RotationUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for nodes.
        /// </summary>
        internal static string ExGather_SearchForNodes {
            get {
                return ResourceManager.GetString("ExGather_SearchForNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip furthest nodes in hotspot. We only want 1..
        /// </summary>
        internal static string ExGather_SkipFurthestNodes {
            get {
                return ResourceManager.GetString("ExGather_SkipFurthestNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping this node, no items we want to gather..
        /// </summary>
        internal static string ExGather_SkipNode {
            get {
                return ResourceManager.GetString("ExGather_SkipNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TouchAndGo strategy override, not waiting for GP unless we are on an ephemeral node.
        /// </summary>
        internal static string ExGather_TnGEphemeral {
            get {
                return ResourceManager.GetString("ExGather_TnGEphemeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TouchAndGo override, maxTimeout being set between 2 and 16 seconds.
        /// </summary>
        internal static string ExGather_TnGOverride {
            get {
                return ResourceManager.GetString("ExGather_TnGOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TouchAndGo strategy override, not waiting for GP unless it is less than 16 seconds.
        /// </summary>
        internal static string ExGather_TnGSeconds {
            get {
                return ResourceManager.GetString("ExGather_TnGSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we should never be here, report error with info GP: {0}, WaitForGp: {1}.
        /// </summary>
        internal static string ExGather_WaitForGp {
            get {
                return ResourceManager.GetString("ExGather_WaitForGp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering without the minimum recommended GP for the rotation.
        /// </summary>
        internal static string ExGather_WithoutMiniumGP {
            get {
                return ResourceManager.GetString("ExGather_WithoutMiniumGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZoneId [{0}], Calling Location {1}.
        /// </summary>
        internal static string ExGather_Zone {
            get {
                return ResourceManager.GetString("ExGather_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to {0}{1}, {2}.
        /// </summary>
        internal static string ExMoveTo_Move {
            get {
                return ResourceManager.GetString("ExMoveTo_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using random location -&gt; {0}.
        /// </summary>
        internal static string ExMoveTo_Random {
            get {
                return ResourceManager.GetString("ExMoveTo_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to Npc -&gt; .
        /// </summary>
        internal static string ExPickupGuildLeve_Move {
            get {
                return ResourceManager.GetString("ExPickupGuildLeve_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking up Leve -&gt; .
        /// </summary>
        internal static string ExPickupGuildLeve_Pickup {
            get {
                return ResourceManager.GetString("ExPickupGuildLeve_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking up Leve: .
        /// </summary>
        internal static string ExPickupGuildLeve_Pickup2 {
            get {
                return ResourceManager.GetString("ExPickupGuildLeve_Pickup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not dismount..
        /// </summary>
        internal static string ExPurify_Dismount {
            get {
                return ResourceManager.GetString("ExPurify_Dismount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not meet the condition to Purify, [{0}].
        /// </summary>
        internal static string ExPurify_GetCondition {
            get {
                return ResourceManager.GetString("ExPurify_GetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to land, can&apos;t reduce unless we land!.
        /// </summary>
        internal static string ExPurify_Land {
            get {
                return ResourceManager.GetString("ExPurify_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not meet the condition to salvage, [{0}].
        /// </summary>
        internal static string ExSalvage_GetCondition {
            get {
                return ResourceManager.GetString("ExSalvage_GetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to land, can&apos;t salvage unless we land!.
        /// </summary>
        internal static string ExSalvage_Land {
            get {
                return ResourceManager.GetString("ExSalvage_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to turn in item {0} -&gt; 0x{1}.
        /// </summary>
        internal static string ExTurnInCollectable_AttemptingTurnin {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_AttemptingTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, could not resolve class type for item:.
        /// </summary>
        internal static string ExTurnInCollectable_ErrorClassType {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_ErrorClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to purchase item {0} in MorDhona, set location to Idyllshire..
        /// </summary>
        internal static string ExTurnInCollectable_FailedPurchaseMorDhona {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_FailedPurchaseMorDhona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout interacting with npc..
        /// </summary>
        internal static string ExTurnInCollectable_InteractingTimeout {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_InteractingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to Npc -&gt; .
        /// </summary>
        internal static string ExTurnInCollectable_Move {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to purchase.
        /// </summary>
        internal static string ExTurnInCollectable_NoItemToPurchase {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_NoItemToPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interacting with Npc -&gt; .
        /// </summary>
        internal static string ExTurnInCollectable_NpcInteract {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_NpcInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing items.
        /// </summary>
        internal static string ExTurnInCollectable_Purchase {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases complete..
        /// </summary>
        internal static string ExTurnInCollectable_PurchaseComplete {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_PurchaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased {5} {0} for {1} {2} scrips at {3} ET; Remaining Scrips: {4}.
        /// </summary>
        internal static string ExTurnInCollectable_Purchased {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout during purchase of {0}.
        /// </summary>
        internal static string ExTurnInCollectable_PurchaseTimeout {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_PurchaseTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrips remaining for shop {0} -&gt; Count: {1}.
        /// </summary>
        internal static string ExTurnInCollectable_ScripsRemaining {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_ScripsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory for {0} -&gt; Count: {1}.
        /// </summary>
        internal static string ExTurnInCollectable_ShopPurchase {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_ShopPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout targeting npc..
        /// </summary>
        internal static string ExTurnInCollectable_TargetingTimeout {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TargetingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning in items.
        /// </summary>
        internal static string ExTurnInCollectable_TurnIn {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t turn in this item for 3 minutes.
        /// </summary>
        internal static string ExTurnInCollectable_TurnInBlackList {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnInBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while turning in the item.
        /// </summary>
        internal static string ExTurnInCollectable_TurnInError {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned in {0} at {1} ET.
        /// </summary>
        internal static string ExTurnInCollectable_TurnInSuccessful {
            get {
                return ResourceManager.GetString("ExTurnInCollectable_TurnInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for transport window..
        /// </summary>
        internal static string ExTurnInGuildLeve_CheckTransport {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_CheckTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting reward on {0} ET.
        /// </summary>
        internal static string ExTurnInGuildLeve_CollectReward {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_CollectReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed on {0} ET.
        /// </summary>
        internal static string ExTurnInGuildLeve_Complete {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to Npc -&gt; .
        /// </summary>
        internal static string ExTurnInGuildLeve_Move {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to turn in. Settings -&gt; HqOnly: {0}, NqOnly: {1}, ItemId: {2}.
        /// </summary>
        internal static string ExTurnInGuildLeve_NoItemToTurnin {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoItemToTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more quests to turn in..
        /// </summary>
        internal static string ExTurnInGuildLeve_NoMoreQuests {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoMoreQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like we don&apos;t have any quests to turn in..
        /// </summary>
        internal static string ExTurnInGuildLeve_NoMoveQuests2 {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoMoveQuests2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rewards left, turn-ins complete..
        /// </summary>
        internal static string ExTurnInGuildLeve_NoRewardsLeft {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NoRewardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have any completed quests left to turn in..
        /// </summary>
        internal static string ExTurnInGuildLeve_NothingToTurnin {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_NothingToTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like no windows are open, lets clear our target and try again..
        /// </summary>
        internal static string ExTurnInGuildLeve_OpenWindow {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting transport option..
        /// </summary>
        internal static string ExTurnInGuildLeve_SelectTransport {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_SelectTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning in items.
        /// </summary>
        internal static string ExTurnInGuildLeve_TurnIn {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned in HQ {0} on {1} ET.
        /// </summary>
        internal static string ExTurnInGuildLeve_TurnInHq {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurnInHq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning in more items on {0} ET.
        /// </summary>
        internal static string ExTurnInGuildLeve_TurninMore {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurninMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned in {0} on {1} ET.
        /// </summary>
        internal static string ExTurnInGuildLeve_TurnInNq {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurnInNq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout while turning in leve..
        /// </summary>
        internal static string ExTurnInGuildLeve_TurninTimeout {
            get {
                return ResourceManager.GetString("ExTurnInGuildLeve_TurninTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting line .
        /// </summary>
        internal static string ExUseAethernet_SelectLine {
            get {
                return ResourceManager.GetString("ExUseAethernet_SelectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout, SelectString window did not open..
        /// </summary>
        internal static string ExUseAethernet_SelectLineTimeout {
            get {
                return ResourceManager.GetString("ExUseAethernet_SelectLineTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision detected! Generating new path!.
        /// </summary>
        internal static string FlightEnabledNavigator_CollisionDetected {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_CollisionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation reached current destination. Within.
        /// </summary>
        internal static string FlightEnabledNavigator_DestinationReached {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_DestinationReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting original Navigator back!.
        /// </summary>
        internal static string FlightEnabledNavigator_Dispose {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing Navigator with Flight Navigator..
        /// </summary>
        internal static string FlightEnabledNavigator_Enabled {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to next hop: {0}{1} D: {2}.
        /// </summary>
        internal static string FlightEnabledNavigator_HopMoving {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_HopMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving to next hop [{0}]: {1}{2} D: {3}.
        /// </summary>
        internal static string FlightEnabledNavigator_HopMoving2 {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_HopMoving2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered trying to find a path. Trying innerNavigator for 10 seconds before re-enabling flight..
        /// </summary>
        internal static string FlightEnabledNavigator_NoPath {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found existing path to {0} using {1} hops in {2} ms.
        /// </summary>
        internal static string FlightEnabledNavigator_PathFound {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_PathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated path to {0} using {1} hops in {2} ms.
        /// </summary>
        internal static string FlightEnabledNavigator_PathGenerated {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_PathGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No viable path found to {0} from {1}.
        /// </summary>
        internal static string FlightEnabledNavigator_PathNotViable {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_PathNotViable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting NavigationProvider to Flight Navigator..
        /// </summary>
        internal static string FlightEnabledNavigator_ResetNavigatonProvider {
            get {
                return ResourceManager.GetString("FlightEnabledNavigator_ResetNavigatonProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default value for flying to false until we can determine if we can fly in this zone..
        /// </summary>
        internal static string FlightEnabledSlideMover_Default {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing took {0} ms or less.
        /// </summary>
        internal static string FlightEnabledSlideMover_Land {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing cancelled after {0} ms. New destination requested..
        /// </summary>
        internal static string FlightEnabledSlideMover_LandCancelled {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing failed. Passing back control..
        /// </summary>
        internal static string FlightEnabledSlideMover_LandFailed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new Landing Unstuck Coroutine, moving to {0}.
        /// </summary>
        internal static string FlightEnabledSlideMover_LandNew {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed Landing Unstuck Coroutine.
        /// </summary>
        internal static string FlightEnabledSlideMover_LandResumed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Landing Task.
        /// </summary>
        internal static string FlightEnabledSlideMover_LandStart {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_LandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff took {0} ms or less.
        /// </summary>
        internal static string FlightEnabledSlideMover_Takeoff {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_Takeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff cancelled after {0} ms. IPlayerMover.Stop() was called..
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffCancelled {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff failed. Passing back control..
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffFailed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new Takeoff Coroutine.
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffNew {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed Takeoff Coroutine.
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffResumed {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Takeoff Task.
        /// </summary>
        internal static string FlightEnabledSlideMover_TakeoffStart {
            get {
                return ResourceManager.GetString("FlightEnabledSlideMover_TakeoffStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MasterPieceSupply] Can&apos;t turn in &apos;{0}&apos; today, the current turn in is &apos;{1}&apos;.
        /// </summary>
        internal static string MasterPieceSupply_CannotTurnIn {
            get {
                return ResourceManager.GetString("MasterPieceSupply_CannotTurnIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MasterPieceSupply] Collectability value &apos;{0}&apos; is too low or we can&apos;t turn in {1} today..
        /// </summary>
        internal static string MasterPieceSupply_CollectabilityValueNotEnough {
            get {
                return ResourceManager.GetString("MasterPieceSupply_CollectabilityValueNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MasterPieceSupply] Not turning in &apos;{0}&apos;, full on scrips..
        /// </summary>
        internal static string MasterPieceSupply_FullScrips {
            get {
                return ResourceManager.GetString("MasterPieceSupply_FullScrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aethernet..
        /// </summary>
        internal static string NoAetheryteUseAethernetReturn_AethernetText {
            get {
                return ResourceManager.GetString("NoAetheryteUseAethernetReturn_AethernetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured during aetherial reduction. Result was {0}.
        /// </summary>
        internal static string PurifyDialog {
            get {
                return ResourceManager.GetString("PurifyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find nearby summoning bell.
        /// </summary>
        internal static string RetainerMaid_NoNearestSummoningBell {
            get {
                return ResourceManager.GetString("RetainerMaid_NoNearestSummoningBell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetainerMaid.
        /// </summary>
        internal static string RetainerMaid_PluginName {
            get {
                return ResourceManager.GetString("RetainerMaid_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An error has occured during desynthesis. Result was {0}&quot;.
        /// </summary>
        internal static string SalvageDialog {
            get {
                return ResourceManager.GetString("SalvageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skywatcher is not enabled in plugins.  Enable it and restart the bot..
        /// </summary>
        internal static string SkyWatcher_CheckEnabled {
            get {
                return ResourceManager.GetString("SkyWatcher_CheckEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skywatcher.
        /// </summary>
        internal static string Skywatcher_PluginName {
            get {
                return ResourceManager.GetString("Skywatcher_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to close the [{0}] window.
        /// </summary>
        internal static string Window_Attempting {
            get {
                return ResourceManager.GetString("Window_Attempting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [{0}] window has been closed..
        /// </summary>
        internal static string Window_Closed {
            get {
                return ResourceManager.GetString("Window_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [{0}] window was not valid, it was either not open or closed on its own..
        /// </summary>
        internal static string Window_invalid {
            get {
                return ResourceManager.GetString("Window_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result while closing [{0}].
        /// </summary>
        internal static string Window_UnexpectedResult {
            get {
                return ResourceManager.GetString("Window_UnexpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0} ms for [{1}] window to close.
        /// </summary>
        internal static string Window_WaitToClose {
            get {
                return ResourceManager.GetString("Window_WaitToClose", resourceCulture);
            }
        }
    }
}
